platform :ios, '13.0'

use_frameworks!

# 공통으로 사용되는 pod들을 정의
def common_pods
  pod 'Alamofire'
  pod 'FirebaseAuth', '~> 11.14.0'
  pod 'FirebaseFirestore', '~> 11.14.0' # Firebase Firestore 최신 버전으로 업데이트
  pod 'FirebaseMessaging', '~> 11.14.0'
end

# SNS 로그인 관련 pod들을 정의
def sns_pods
  pod 'KakaoSDKCommon'
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKUser'
  pod 'naveridlogin-sdk-ios'
  pod 'GoogleSignIn'
end
def sns_google
  pod 'GoogleSignIn'
end

# 광고 관련 pod들을 정의
def ad_pods
  pod 'Google-Mobile-Ads-SDK'
end


target 'lu_rootstudycenter' do
  common_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'BoringSSL-GRPC'
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
          flags = file.settings['COMPILER_FLAGS'].split
          flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
          file.settings['COMPILER_FLAGS'] = flags.join(' ')
        end
      end
    end
  end
end